/**
 * File Name    : ITrigger.cls
 * Author       : da.kim
 * Date         : 2023-05-23
 * Tester       : TriggerHandler_Test.cls
 * Description  : 동적 트리거핸들러 실행을 위한 인터페이스 클래스
 * Modification Log
 * ======================================================================================
 * Ver      Date          Author              Modification
 * ======================================================================================
 * 1.0      2023-05-23    da.kim              Create
**/
public interface ITrigger {
    // Run Trigger Handler method
    void run();
}
